import { CozyAnimeTheme, ThemeConfig } from "@/types/theme";

export const DEFAULT_THEME: CozyAnimeTheme = "night-study";

export const THEME_ORDER: CozyAnimeTheme[] = [
  "night-study",
  "rainy-evening",
  "sunset-study",
  "lantern-library",
  "rooftop-bluehour",
  "train-window",
  "forest-cabin",
  "cherry-dawn",
  "violet-sky",
  "forest-green",
  "anime-sky",
  "sakura-street",
  "ocean-horizon",
  "misty-mountains",
  "cozy-cafe",
];

export const COZY_THEMES: Record<CozyAnimeTheme, ThemeConfig> = {
  "night-study": {
    id: "night-study",
    name: "Night Study",
    jpName: "夜の勉強",
    description: "Moonlit rooftops and a warm desk lamp for quiet focus",
    backgroundUrl: "/themes/night-study.jpg",
    previewColor: "#091424",
    accentColor: "#F6C76D",
    ambientType: "stars",
    sceneAlt: "Real nighttime workspace with a desk lamp, laptop, and shelves",
    group: "Anime Rooms",
    brightness: "low",
    dominantColor: "blue",
  },
  "rainy-evening": {
    id: "rainy-evening",
    name: "Rainy Evening",
    jpName: "雨の夕暮れ",
    description: "Blue-gray window light and soft city reflections",
    backgroundUrl: "/themes/rainy-evening.jpg",
    previewColor: "#0F2030",
    accentColor: "#A8DDEB",
    ambientType: "rain",
    sceneAlt: "Real rain-covered window with blurred city lights",
    group: "Anime Rooms",
    brightness: "low",
    dominantColor: "blue",
  },
  "sunset-study": {
    id: "sunset-study",
    name: "Sunset Study",
    jpName: "夕暮れの部屋",
    description: "Peach light, soft clouds, and a gentle golden-hour desk",
    backgroundUrl: "/themes/sunset-study.jpg",
    previewColor: "#2D1E31",
    accentColor: "#F6B375",
    ambientType: "dust",
    sceneAlt: "Real desk with a lamp and warm sunset through a window",
    group: "Anime Rooms",
    brightness: "high",
    dominantColor: "peach",
  },
  "lantern-library": {
    id: "lantern-library",
    name: "Lantern Library",
    jpName: "灯りの図書室",
    description: "Tall shelves, paper textures, and a single warm pool of light",
    backgroundUrl: "/themes/lantern-library.jpg",
    previewColor: "#211a2a",
    accentColor: "#f2bf70",
    ambientType: "dust",
    sceneAlt: "Real library interior lit by a vintage brass desk lamp",
    group: "Anime Rooms",
    brightness: "medium",
    dominantColor: "gold",
  },
  "rooftop-bluehour": {
    id: "rooftop-bluehour",
    name: "Rooftop Blue Hour",
    jpName: "青い屋上",
    description: "A quiet city edge where the first stars meet the last light",
    backgroundUrl: "/themes/rooftop-bluehour.jpg",
    previewColor: "#111c3a",
    accentColor: "#9eb8ff",
    ambientType: "stars",
    sceneAlt: "Real city view from a rooftop during blue hour",
    group: "Ambient Worlds",
    brightness: "low",
    dominantColor: "purple",
  },
  "train-window": {
    id: "train-window",
    name: "Last Train Window",
    jpName: "終電の窓",
    description: "Passing lights turn an evening commute into a small film",
    backgroundUrl: "/themes/train-window.jpg",
    previewColor: "#18263a",
    accentColor: "#a8ddeb",
    ambientType: "rain",
    sceneAlt: "Real train at night with illuminated windows",
    group: "Ambient Worlds",
    brightness: "medium",
    dominantColor: "blue",
  },
  "forest-cabin": {
    id: "forest-cabin",
    name: "Forest Cabin",
    jpName: "森の小屋",
    description: "Evergreen silhouettes and a desk tucked beside the glass",
    backgroundUrl: "/themes/forest-cabin.jpg",
    previewColor: "#132b2a",
    accentColor: "#9bd59d",
    ambientType: "dust",
    sceneAlt: "Real cabin with large windows in a forest clearing",
    group: "Ambient Worlds",
    brightness: "medium",
    dominantColor: "green",
  },
  "cherry-dawn": {
    id: "cherry-dawn",
    name: "Cherry Dawn",
    jpName: "桜の朝",
    description: "Soft morning peach with a branch moving at the window",
    backgroundUrl: "/themes/cherry-dawn.jpg",
    previewColor: "#4a2b45",
    accentColor: "#ffc3d8",
    ambientType: "dust",
    sceneAlt: "Real pink cherry blossoms seen through a window",
    group: "Gradients & Colors",
    brightness: "high",
    dominantColor: "peach",
  },
  "violet-sky": {
    id: "violet-sky",
    name: "Violet Sky",
    jpName: "紫の空",
    description: "A clean dusk gradient for a lighter, less literal room",
    backgroundUrl: "/themes/violet-sky.jpg",
    previewColor: "#241b47",
    accentColor: "#d4b6ff",
    ambientType: "stars",
    sceneAlt: "Real purple sky over silhouetted mountains at dusk",
    group: "Gradients & Colors",
    brightness: "medium",
    dominantColor: "purple",
  },
  "forest-green": {
    id: "forest-green",
    name: "Forest Green",
    jpName: "緑の森",
    description: "Deep leaves, filtered daylight, and a quiet trail for longer sessions",
    backgroundUrl: "/themes/forest-green.jpg",
    previewColor: "#0f2a24",
    accentColor: "#9ad6a1",
    ambientType: "dust",
    sceneAlt: "Real sunlit green forest with a path beneath dense leaves",
    group: "Ambient Worlds",
    brightness: "medium",
    dominantColor: "green",
  },
  "anime-sky": {
    id: "anime-sky",
    name: "Anime Sky",
    jpName: "空色の午後",
    description: "Pastel clouds and open blue space for a clear-headed reset",
    backgroundUrl: "/themes/anime-sky.jpg",
    previewColor: "#41688f",
    accentColor: "#f4bfd4",
    ambientType: "dust",
    sceneAlt: "Real pastel pink clouds drifting across a bright blue sky",
    group: "Gradients & Colors",
    brightness: "high",
    dominantColor: "peach",
  },
  "sakura-street": {
    id: "sakura-street",
    name: "Sakura Street",
    jpName: "桜並木",
    description: "A soft spring walk in full bloom, gentle enough for reading",
    backgroundUrl: "/themes/sakura-street.jpg",
    previewColor: "#3b2542",
    accentColor: "#ffb6c9",
    ambientType: "dust",
    sceneAlt: "Real pink sakura tree in bloom against a soft sky",
    group: "Gradients & Colors",
    brightness: "high",
    dominantColor: "peach",
  },
  "ocean-horizon": {
    id: "ocean-horizon",
    name: "Ocean Horizon",
    jpName: "海の水平線",
    description: "Long blue lines, low visual noise, and space to breathe",
    backgroundUrl: "/themes/ocean-horizon.jpg",
    previewColor: "#0d2c42",
    accentColor: "#8fd4e8",
    ambientType: "dust",
    sceneAlt: "Real calm blue ocean meeting a clear sky at the horizon",
    group: "Ambient Worlds",
    brightness: "medium",
    dominantColor: "blue",
  },
  "misty-mountains": {
    id: "misty-mountains",
    name: "Misty Mountains",
    jpName: "霧の山々",
    description: "Layered green hills softened by cloud and distance",
    backgroundUrl: "/themes/misty-mountains.jpg",
    previewColor: "#182a2b",
    accentColor: "#b5d7c5",
    ambientType: "dust",
    sceneAlt: "Real layered green mountains fading into mist beneath clouds",
    group: "Ambient Worlds",
    brightness: "low",
    dominantColor: "green",
  },
  "cozy-cafe": {
    id: "cozy-cafe",
    name: "Cozy Café",
    jpName: "あたたかい喫茶店",
    description: "Wood, green leaves, and warm tables for a gentle evening routine",
    backgroundUrl: "/themes/cozy-cafe.jpg",
    previewColor: "#34231d",
    accentColor: "#f2c27b",
    ambientType: "dust",
    sceneAlt: "Real cozy café interior with plants, wood furniture, and warm light",
    group: "Anime Rooms",
    brightness: "medium",
    dominantColor: "gold",
  },
};
