import { CozyAnimeTheme, ThemeConfig } from "@/types/theme";

export const DEFAULT_THEME: CozyAnimeTheme = "night-study";

export const THEME_ORDER: CozyAnimeTheme[] = [
  "night-study",
  "rainy-evening",
  "sunset-study",
  "lantern-library",
  "rooftop-bluehour",
  "train-window",
  "forest-cabin",
  "cherry-dawn",
  "violet-sky",
  "forest-green",
  "anime-sky",
  "sakura-street",
  "ocean-horizon",
  "misty-mountains",
  "cozy-cafe",
];

export const COZY_THEMES: Record<CozyAnimeTheme, ThemeConfig> = {
  "night-study": {
    id: "night-study",
    name: "Night Study",
    jpName: "夜の勉強",
    description: "Moonlit rooftops and a warm desk lamp for quiet focus",
    backgroundUrl: "/themes/night-study.webp",
    previewColor: "#091424",
    accentColor: "#F6C76D",
    ambientType: "stars",
    sceneAlt: "Illustrated moonlit study room with an open notebook, desk lamp, and distant rooftops",
    group: "Anime Rooms",
    brightness: "low",
    dominantColor: "blue",
  },
  "rainy-evening": {
    id: "rainy-evening",
    name: "Rainy Evening",
    jpName: "雨の夕暮れ",
    description: "Blue-gray window light and soft city reflections",
    backgroundUrl: "/themes/rainy-evening.webp",
    previewColor: "#0F2030",
    accentColor: "#A8DDEB",
    ambientType: "rain",
    sceneAlt: "Illustrated rain-streaked apartment window with muted city reflections and a quiet desk",
    group: "Anime Rooms",
    brightness: "low",
    dominantColor: "blue",
  },
  "sunset-study": {
    id: "sunset-study",
    name: "Sunset Study",
    jpName: "夕暮れの部屋",
    description: "Peach light, soft clouds, and a gentle golden-hour desk",
    backgroundUrl: "/themes/sunset-study.webp",
    previewColor: "#2D1E31",
    accentColor: "#F6B375",
    ambientType: "dust",
    sceneAlt: "Illustrated golden-hour bedroom desk beneath peach clouds and long soft shadows",
    group: "Anime Rooms",
    brightness: "high",
    dominantColor: "peach",
  },
  "lantern-library": {
    id: "lantern-library",
    name: "Lantern Library",
    jpName: "灯りの図書室",
    description: "Tall shelves, paper textures, and a single warm pool of light",
    backgroundUrl: "/themes/lantern-library.webp",
    previewColor: "#211a2a",
    accentColor: "#f2bf70",
    ambientType: "dust",
    sceneAlt: "Illustrated tall library shelves with paper textures and one pool of brass-lamp light",
    group: "Anime Rooms",
    brightness: "medium",
    dominantColor: "gold",
  },
  "rooftop-bluehour": {
    id: "rooftop-bluehour",
    name: "Rooftop Blue Hour",
    jpName: "青い屋上",
    description: "A quiet city edge where the first stars meet the last light",
    backgroundUrl: "/themes/rooftop-bluehour.webp",
    previewColor: "#111c3a",
    accentColor: "#9eb8ff",
    ambientType: "stars",
    sceneAlt: "Illustrated empty school rooftop at blue hour with a city edge and first stars",
    group: "Ambient Worlds",
    brightness: "low",
    dominantColor: "purple",
  },
  "train-window": {
    id: "train-window",
    name: "Last Train Window",
    jpName: "終電の窓",
    description: "Passing lights turn an evening commute into a small film",
    backgroundUrl: "/themes/train-window.webp",
    previewColor: "#18263a",
    accentColor: "#a8ddeb",
    ambientType: "rain",
    sceneAlt: "Illustrated quiet last-train carriage with passing evening lights beyond the window",
    group: "Ambient Worlds",
    brightness: "medium",
    dominantColor: "blue",
  },
  "forest-cabin": {
    id: "forest-cabin",
    name: "Forest Cabin",
    jpName: "森の小屋",
    description: "Evergreen silhouettes and a desk tucked beside the glass",
    backgroundUrl: "/themes/forest-cabin.webp",
    previewColor: "#132b2a",
    accentColor: "#9bd59d",
    ambientType: "dust",
    sceneAlt: "Illustrated study desk beside a cabin window with evergreen silhouettes outside",
    group: "Ambient Worlds",
    brightness: "medium",
    dominantColor: "green",
  },
  "cherry-dawn": {
    id: "cherry-dawn",
    name: "Open Sky",
    jpName: "Sky Desk",
    description: "Wide blue sky over a quiet rooftop study desk",
    backgroundUrl: "/themes/cherry-dawn.webp",
    previewColor: "#4d9fd6",
    accentColor: "#f4b85e",
    ambientType: "dust",
    sceneAlt: "Illustrated rooftop study desk beneath a wide blue sky and layered clouds",
    group: "Anime Rooms",
    brightness: "high",
    dominantColor: "blue",
  },
  "violet-sky": {
    id: "violet-sky",
    name: "Violet Sky",
    jpName: "紫の空",
    description: "A clean dusk gradient for a lighter, less literal room",
    backgroundUrl: "/themes/violet-sky.webp",
    previewColor: "#241b47",
    accentColor: "#d4b6ff",
    ambientType: "stars",
    sceneAlt: "Illustrated minimal dusk study room opening toward violet mountain silhouettes",
    group: "Gradients & Colors",
    brightness: "medium",
    dominantColor: "purple",
  },
  "forest-green": {
    id: "forest-green",
    name: "Forest Green",
    jpName: "緑の森",
    description: "Deep leaves, filtered daylight, and a quiet trail for longer sessions",
    backgroundUrl: "/themes/forest-green.webp",
    previewColor: "#0f2a24",
    accentColor: "#9ad6a1",
    ambientType: "dust",
    sceneAlt: "Illustrated reading shelter beside a sunlit forest path and dense leaves",
    group: "Ambient Worlds",
    brightness: "medium",
    dominantColor: "green",
  },
  "anime-sky": {
    id: "anime-sky",
    name: "Anime Sky",
    jpName: "空色の午後",
    description: "Pastel clouds and open blue space for a clear-headed reset",
    backgroundUrl: "/themes/anime-sky.webp",
    previewColor: "#41688f",
    accentColor: "#f4bfd4",
    ambientType: "dust",
    sceneAlt: "Illustrated open classroom windows beneath an expansive blue sky and pastel clouds",
    group: "Gradients & Colors",
    brightness: "high",
    dominantColor: "peach",
  },
  "sakura-street": {
    id: "sakura-street",
    name: "Sakura Street",
    jpName: "桜並木",
    description: "A soft spring walk in full bloom, gentle enough for reading",
    backgroundUrl: "/themes/sakura-street.webp",
    previewColor: "#3b2542",
    accentColor: "#ffb6c9",
    ambientType: "dust",
    sceneAlt: "Illustrated quiet residential study nook overlooking a spring sakura street",
    group: "Gradients & Colors",
    brightness: "high",
    dominantColor: "peach",
  },
  "ocean-horizon": {
    id: "ocean-horizon",
    name: "Ocean Horizon",
    jpName: "海の水平線",
    description: "Long blue lines, low visual noise, and space to breathe",
    backgroundUrl: "/themes/ocean-horizon.webp",
    previewColor: "#0d2c42",
    accentColor: "#8fd4e8",
    ambientType: "dust",
    sceneAlt: "Illustrated calm seaside reading room with long ocean and sky lines",
    group: "Ambient Worlds",
    brightness: "medium",
    dominantColor: "blue",
  },
  "misty-mountains": {
    id: "misty-mountains",
    name: "Misty Mountains",
    jpName: "霧の山々",
    description: "Layered green hills softened by cloud and distance",
    backgroundUrl: "/themes/misty-mountains.webp",
    previewColor: "#182a2b",
    accentColor: "#b5d7c5",
    ambientType: "dust",
    sceneAlt: "Illustrated mountain study lodge with layered green ridges softened by mist",
    group: "Ambient Worlds",
    brightness: "low",
    dominantColor: "green",
  },
  "cozy-cafe": {
    id: "cozy-cafe",
    name: "Cozy Café",
    jpName: "あたたかい喫茶店",
    description: "Wood, green leaves, and warm tables for a gentle evening routine",
    backgroundUrl: "/themes/cozy-cafe.webp",
    previewColor: "#34231d",
    accentColor: "#f2c27b",
    ambientType: "dust",
    sceneAlt: "Illustrated empty after-hours cafe study table with wood, plants, and warm pendant light",
    group: "Anime Rooms",
    brightness: "medium",
    dominantColor: "gold",
  },
};
